language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - pip install -r requirements.txt
  - pip install coveralls
branches:
  only:
  - BucketList
# command to run tests
script: "coverage run --omit='*virtualenv*' -m unittest discover"
after_success: coveralls
env:
  global:
    - TRAVIS_BUILD=true
