language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r requirements.txt"
branches:
  only:
  - BucketList
# command to run tests
script: "python -m unittest discover"
env:
  global:
    - TRAVIS_BUILD=true
